[phases.setup]
# Ensure Node.js is installed for server build
nixPkgs = ["nodejs_20"]

[phases.build]
cmds = ["cd server && npm install"]

[start]
cmd = "cd server && INWORLD_API_KEY=2740oa1ZqOpx8SJgbybPuV8PIKnZ9ULP ASSEMBLY_AI_API_KEY=401613b01ebe47589f861809b3f402f9 npm run start"
